{{- $length := len .Values.services }}
{{- range $key, $value := .Values.ingresses }}
{{- $services := $.Values.services }}
{{- $currentService := index $services $key }}
{{- if and ($value.enabled) ($currentService.enabled) -}}
{{- $fullName := include "rds_exporter.fullname" $ -}}
{{- $ingressPath := $value.path -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $key }}
  labels:
    app: {{ template "rds_exporter.name" $ }}-{{ $key }}
    chart: {{ template "rds_exporter.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    tribe: {{ $.Values.tribe }}
    squad: {{ $.Values.squad }}
{{- with $value.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range $value.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              {{- if eq $length 1 }}
              serviceName: {{ $fullName }}-k8s
              {{- else }}
              serviceName: {{ $fullName }}-{{ $key }}-k8s
              {{- end }}
              servicePort: http
{{ end }}
{{- end }}
{{- end }}
